using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DICJ_Ipsum
{
    static class DictionnaireInfo
    {
        public static Dictionary<int, string> DicoInfo = new Dictionary<int, string>()
        {
            {1, "C#"},
            {2, "C++" },
            {3, "C" },
            {4, "Java" },
            {5, "Javascript" },
            {6, "Assembleur" },
            {7, "ASP.NET"},
            {8, "BASIC"},
            {9, "Chrome" },
            {10, "COBOL" },
            {11, "CobolScript" },
            {12, "CoffeeScript" },
            {13, "CSS" },
            {14, "Fortran" },
            {15, "Kotlin" },
            {16, "Lisp" },
            {17, "Node.js" },
            {18, "PHP" },
            {19, "PowerShell" },
            {20, "Python" },
            {21, "Ruby" },
            {22, "Rust" },
            {23, "UNITY" },
            {24, "unityscript" },
            {25, "Unix shell" },
            {26, "UnrealScript" },
            {27, "VBA" },
            {28, "VBScript" },
            {29, "Admin" },
            {30, "Ordinateur" },
            {31, "Réalité virtuelle" },
            {32, "Réalité augmentée" },
            {33, "Technologie" },
            {34, "Binaire" },
            {35, "Hexadécimal" },
            {36, "Bit" },
            {37, "Octet" },
            {38, "Go" },
            {39, "Trame" },
            {40, "Segment" },
            {41, "Paquet" },
            {42, "To" },
            {43, "Mo" },
            {44, "Ko" },
            {45, "true" },
            {46, "false" },
            {47, "goto" },
            {48, "BD" },
            {49, "CRUD" },
            {50, "Contraintes" },
            {51, "Procédures stockées" },
            {52, "Programmation" },
            {53, "Mobile" },
            {54, "Jeux" },
            {55, "Android" },
            {56, "if" },
            {57, "else" },
            {58, "else if" },
            {59, "for" },
            {60, "while" },
            {61, "do" },
            {62, "switch" },
            {63, "Commutateur" },
            {64, "break" },
            {65, "case" },
            {66, "try" },
            {67, "catch" },
            {68, "finally" },
            {69, "Razor" },
            {70, "Bootstrap" },
            {71, "HTML" },
            {72, "JQuery" },
            {73, "DOM" },
            {74, "Bug" },
            {75, "Debug" },
            {76, "Point d'arrêt" },
            {77, "StackOverflow" },
            {78, "OutOfRangeException" },
            {79, "Exception" },
            {80, "Classe" },
            {81, "Interface" },
            {82, "Polymorphisme" },
            {83, "Héritage" },
            {84, "Fonction" },
            {85, "Paramètres" },
            {86, "DELETE" },
            {87, "UPDATE" },
            {88, "CREATE" },
            {89, "INSERT" },
            {90, "Propriétés" },
            {91, "Méthodes" },
            {92, "Attributs" },
            {93, "string" },
            {94, "cast" },
            {95, "int" },
            {96, "bool" },
            {97, "array" },
            {98, "Console" },
            {99, "System" },
            {100, "Validation" },
            {101, "Réseau" },
            {102, "Support technique" },
            {103, "Programmeur" },
            {104, "Front-end" },
            {105, "Back-end" },
            {106, "Technicien" },
            {107, "RJ-45" },
            {108, "Routeur" },
            {109, "IPv4" },
            {110, "IPv6" },
            {111, "cmd" },
            {112, "var" },
            {113, "Surcharge" },
            {114, "static" },
            {115, "double" },
            {116, "float" },
            {117, "DateTime" },
            {118, "blob" },
            {119, "varchar" },
            {120, "AUTO_INCREMENT" },
            {121, "Primary key" },
            {122, "Foreign key" },
            {123, "JOIN" },
            {124, "INNER JOIN" },
            {125, "OUTER JOIN" },
            {126, "LEFT JOIN" },
            {127, "RIGHT JOIN" },
            {128, "char" },
            {129, "float" },
            {130, "SQL" },
            {131, "Triggers" },
            {132, "Vecteurs" },
            {133, "Widgets" },
            {134, "LINQ" },
            {135, "Entity" },
            {136, "MySQL" },
            {137, "WAMP" },
            {138, "Serveur" },
            {139, "FTP" },
            {140, "DNS" },
            {141, "DHCP" },
            {142, "Informatique" },
            {143, "Processeur" },
            {144, "Design" },
            {145, "Web" },
            {146, "Graphique" },
            {147, "Code" },
            {148, "USB" },
            {149, "Requêtes" },
            {150, "Pointeur" },
            {151, "Variables" },
            {152, "Constantes" },
            {153, "abstract" },
            {154, "override" },
            {155, "new" },
            {156, "Clavier" },
            {157, "Souris"},
            {158, "cloud" },
            {159, "BYOD" },
            {160, "Visual Studio" },
            {161, "Notepad++" },
            {162, "Android Studio" },
            {163, "PHPStorm" },
            {164, "IntelliJ" },
            {165, "Git" },
            {166, "GitHub" },
            {167, "Dépôt" },
            {168, "Logique" },
            {169, "Récursivité" },
            {170, "Modélisation" },
            {171, "SCRUM" },
            {172, "Schémas" },
            {173, "Commit" },
            {174, "Push" },
            {175, "Pull" },
            {176, "Fetch" },
            {177, "Stage" },
            {178, "FatalError" },
            {179, "Syntaxe" },
            {180, "NVRAM" },
            {181, "Cisco" },
            {182, "RAM" },
            {183, "BIOS" },
            {184, "Système d'exploitation" },
            {185, "ROM" },
            {186, "Linux" },
            {187, "Ubuntu" },
            {188, "Mac" },
            {189, "IOS" },
            {190, "File" },
            {191, "Pile" },
            {192, "Pile" },
            {193, "Objets" },
            {194, "Listes" },
            {195, "Regex" },
            {196, "Protocoles" },
            {197, "Connecteurs" },
            {198, "Windows" },
            {199, "Algorithme" },
            {200, ".NET" },
            {201, "ARPANET" },
            {202, "Internet" },
            {203, "Intranet" },
            {204, "WAN" },
            {205, "LAN" },
            {206, "MAN" },
            {207, "WLAN" },
            {208, "Ethernet" },
            {209, "foreach" },
            {210, "public" },
            {211, "private" },
            {212, "protected" },
            {213, "null"},
            {214, "Save" },
            {215, "namespace" },
            {216, "WindowsForm" },
            {217, "SELECT" },
            {218, "FROM" },
            {219, "WHERE" },
            {220, "T-SQL" },
            {221, "Curseur" },
            {222, "Modèle OSI" },
            {223, "Modèle TCP/IP" },
            {224, "Segmentation" },
            {225, "VLSM" },
            {226, "Topologie" },
            {227, "Sécurité" },
            {228, "Hacking" },
            {229, "TFTP" },
            {230, "WPA" },
            {231, "WPA2" },
            {232, "Configuration" },
            {233, "Dépannage" },
            {234, "Objets connectés" },
            {235, "LTE" },
            {236, "3G" },
            {237, "4G" },
            {238, "CSHTML" },
            {239, "Recherche Google" },
            {240, "Café" },
            {241, "CTRL-C" },
            {242, "CTRL-V" },
            {243, "Références" },
            {244, "Librairies" },
            {245, "DLL" },
            {246, "ASCII" },
            {247, "Modèle" },
            {248, "Vue" },
            {249, "Controlleur" },
            {250, "Main" }
        };
    }
}
